package com.jerry.boxes.ui.boxes.shapes

enum class Shape(val group: ShapeGroup) {
    Box(ShapeGroup.BASIC),
    Circle(ShapeGroup.BASIC),
    Star(ShapeGroup.BASIC),
    TriangleBottomLeft(ShapeGroup.CORNER),
    TriangleBottomRight(ShapeGroup.CORNER),
    TriangleTopLeft(ShapeGroup.CORNER),
    TriangleTopRight(ShapeGroup.CORNER),
    RectangleLeft(ShapeGroup.RECTANGLE),
    RectangleRight(ShapeGroup.RECTANGLE),
    RectangleTop(ShapeGroup.RECTANGLE),
    RectangleBottom(ShapeGroup.RECTANGLE),
    ArcCornerRight(ShapeGroup.CORNER_ARC),
    ArcCornerLeft(ShapeGroup.CORNER_ARC),
    ArcCornerRightInverse(ShapeGroup.CORNER_ARC),
    ArcCornerLeftInverse(ShapeGroup.CORNER_ARC),
    BoxTopLeft(ShapeGroup.CORNER),
    BoxBottomLeft(ShapeGroup.CORNER),
    BoxTopRight(ShapeGroup.CORNER),
    BoxBottomRight(ShapeGroup.CORNER),
    Diamond(ShapeGroup.BASIC),
    ArcLeft(ShapeGroup.ARC),
    ArcRight(ShapeGroup.ARC),
    ArcTop(ShapeGroup.ARC),
    ArcBottom(ShapeGroup.ARC),
    VerticalLine(ShapeGroup.LINE),
    HorizontalLine(ShapeGroup.LINE),
    TopLeftToBottomRightLine(ShapeGroup.LINE),
    BottomLeftToTopRightLine(ShapeGroup.LINE)
}