import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.plugin.parcelize'
    id 'com.google.devtools.ksp'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'com.github.ben-manes.versions'
    id 'org.jlleitschuh.gradle.ktlint'
}

android {
    namespace 'com.jerry.shapes'
    compileSdk 37

    defaultConfig {
        applicationId "com.jerry.shapes"
        minSdk 24
        targetSdk 37
        versionCode 3
        versionName "1.02"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    ktlint {
        android.set(true) // Enables Android-specific rules
        ignoreFailures.set(false) // Fails the build if issues are found
        reporters {
            reporter(ReporterType.PLAIN)
        }
    }

    signingConfigs {
        release {
            keyAlias 'RouteSucks'
            keyPassword 'RouteSucks'
            storeFile file('../../key.jks')
            storePassword 'RouteSucks'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_21
            freeCompilerArgs.addAll(
                    "-opt-in=kotlin.RequiresOptIn",
                    "-opt-in=androidx.compose.animation.ExperimentalAnimationApi",
                    "-opt-in=androidx.lifecycle.compose.ExperimentalLifecycleComposeApi",
                    "-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi",
                    "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api",
                    "-Xjvm-default=all-compatibility"
            )
        }
    }

    buildFeatures {
        compose true
        buildConfig true
    }
    packaging {
        resources {
            excludes.add('/META-INF/{AL2.0,LGPL2.1}')
            excludes.add('META-INF/LICENSE.md')
            excludes.add('META-INF/LICENSE-notice.md')
        }
    }
}

dependencies {

    implementation platform('com.google.firebase:firebase-bom:34.15.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'

    implementation "androidx.core:core-ktx:$coreKtx"
    implementation "androidx.activity:activity-compose:$composeActivity"
    implementation "androidx.compose.ui:ui:$compose"
    implementation "androidx.compose.ui:ui-util:$compose"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose"
    implementation "androidx.compose.material3:material3:$material3"
    implementation "androidx.datastore:datastore-preferences:1.2.1"
    implementation "androidx.core:core-splashscreen:1.2.0"

    // TODO replace with navigation 3
    implementation "io.github.raamcosta.compose-destinations:animations-core:$composeDestinations"
    ksp "io.github.raamcosta.compose-destinations:ksp:$composeDestinations"

    implementation "io.insert-koin:koin-android:$koin"
    implementation "io.insert-koin:koin-androidx-compose:$koinCompose"

    implementation "androidx.lifecycle:lifecycle-runtime-compose:$lifecycle"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle"

    implementation "com.squareup.retrofit2:retrofit:$retrofit"
    implementation "com.squareup.moshi:moshi:$moshi"
    ksp "com.squareup.moshi:moshi-kotlin-codegen:$moshi"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofit"

    implementation "androidx.room:room-runtime:$room"
    implementation "androidx.room:room-ktx:$room"
    implementation "androidx.room:room-paging:$room"
    ksp "androidx.room:room-compiler:$room"

    implementation "io.coil-kt:coil-compose:$coil"
    implementation "com.jakewharton.timber:timber:$timber"

    implementation 'com.godaddy.android.colorpicker:compose-color-picker-android:0.7.0'

    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:$desugarJdkLib"

    testImplementation "junit:junit:$junit"
    testImplementation "io.mockk:mockk:$ioMock"
    testImplementation "app.cash.turbine:turbine:$turbine"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutines"

    implementation("androidx.paging:paging-runtime-ktx:$paging")
    implementation("androidx.paging:paging-compose:$composePaging")

    androidTestImplementation "androidx.test.ext:junit:$junitExt"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose"
    androidTestImplementation "app.cash.turbine:turbine:$turbine"

    debugImplementation "androidx.compose.ui:ui-tooling:$compose"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose"
}